version: '3.8'

networks:
  rocketmq-net:
    driver: bridge

services:
  # NameServer
  namesrv:
    image: apache/rocketmq:5.1.0
    container_name: rocketmq-namesrv
    ports:
      - "9876:9876"
    volumes:
      - ./data/namesrv/logs:/root/data/rocketmq/logs
      - ./data/namesrv/store:/root/data/rocketmq/store
    environment:
      - MAX_HEAP_SIZE=4G
      - HEAP_NEWSIZE=4G
    networks:
      - rocketmq-net
    command: sh mqnamesrv

  # Broker
  broker:
    image: apache/rocketmq:5.1.0
    container_name: rocketmq-broker
    user: "root"
    ports:
      - "10909:10909"
      - "10911:10911"
      - "10912:10912"
    volumes:
      - ./data/broker/logs:/root/data/rocketmq/logs
      - ./data/broker/store:/root/data/rocketmq/store
      - ./conf/broker.conf:/root/data/rocketmq/conf/broker.conf
    environment:
      - NAMESRV_ADDR=namesrv:9876
    depends_on:
      - namesrv
    networks:
      - rocketmq-net
    command: sh mqbroker -c /root/data/rocketmq/conf/broker.conf

  console:
    image: apacherocketmq/rocketmq-dashboard:latest
    container_name: rocketmq-console
    ports:
      - "8082:8082"
    environment:
      - JAVA_OPTS=-Drocketmq.namesrv.addr=9.135.33.28:9876
    depends_on:
      - namesrv
      - broker
    networks:
      - rocketmq-net