version: "3"
services:
  mysql:
    image: 'mysql'
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=fuxudong
    volumes:
      - D:\program\docker\data\mysql:/var/lib/mysql